---
name: Update Transcript Daily

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  update-transcript:
    runs-on: ubuntu-latest
    environment: transcript  # Use the transcript environment for secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update transcript data
        run: |
          python passed_exams.py "${{ secrets.TRANSCRIPT_CODE }}" \
            --locale en-gb --output passed_exams.csv

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add passed_exams.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update passed_exams.csv with latest transcript data"
            git push
          fi